/**
 * Catálogo de emojis por categoría con palabras clave (ES/EN) para el buscador.
 * No pretende ser el set Unicode completo (sería enorme); es una selección amplia
 * y útil estilo Teams/WhatsApp. Cada entrada: `e` = emoji, `k` = keywords.
 *
 * Fuente única de verdad del selector de emojis (EmojiStickerPicker) y del
 * autocompletado de shortcodes (`:nombre:`) del composer.
 */
export interface EmojiCategory {
  id: string;
  label: string;
  /** Glifo que representa la categoría en las pestañas del selector. */
  glyph: string;
  emojis: { e: string; k: string[] }[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Caras y emociones',
    glyph: '😀',
    emojis: [
      { e: '😀', k: ['sonrisa', 'feliz', 'grin', 'happy'] },
      { e: '😃', k: ['sonrisa', 'alegre', 'smile'] },
      { e: '😄', k: ['risa', 'feliz', 'laugh'] },
      { e: '😁', k: ['sonrisa', 'dientes', 'beam'] },
      { e: '😆', k: ['risa', 'carcajada', 'laughing'] },
      { e: '😅', k: ['risa', 'sudor', 'sweat', 'nervioso'] },
      { e: '🤣', k: ['risa', 'piso', 'rofl', 'lol'] },
      { e: '😂', k: ['llorar', 'risa', 'joy', 'lol'] },
      { e: '🙂', k: ['sonrisa', 'ligera', 'slight'] },
      { e: '🙃', k: ['reves', 'sarcasmo', 'upside'] },
      { e: '😉', k: ['guiño', 'wink', 'coqueto'] },
      { e: '😊', k: ['sonrojo', 'tierno', 'blush', 'feliz'] },
      { e: '😇', k: ['angel', 'santo', 'halo'] },
      { e: '🥰', k: ['amor', 'corazones', 'love'] },
      { e: '😍', k: ['amor', 'ojos', 'heart eyes'] },
      { e: '🤩', k: ['estrella', 'asombro', 'star struck'] },
      { e: '😘', k: ['beso', 'kiss'] },
      { e: '😗', k: ['beso', 'kiss'] },
      { e: '😋', k: ['rico', 'sabroso', 'yum'] },
      { e: '😛', k: ['lengua', 'tongue'] },
      { e: '😜', k: ['guiño', 'lengua', 'loco'] },
      { e: '🤪', k: ['loco', 'zany', 'goofy'] },
      { e: '🤨', k: ['ceja', 'duda', 'raised eyebrow'] },
      { e: '🧐', k: ['monoculo', 'pensar', 'monocle'] },
      { e: '🤓', k: ['nerd', 'gafas', 'geek'] },
      { e: '😎', k: ['cool', 'gafas', 'sunglasses'] },
      { e: '🥳', k: ['fiesta', 'party', 'celebrar'] },
      { e: '😏', k: ['picaro', 'smirk'] },
      { e: '😒', k: ['fastidio', 'unamused'] },
      { e: '😞', k: ['triste', 'decepcion', 'sad'] },
      { e: '😔', k: ['pensativo', 'triste', 'pensive'] },
      { e: '😟', k: ['preocupado', 'worried'] },
      { e: '😕', k: ['confundido', 'confused'] },
      { e: '🙁', k: ['triste', 'frown'] },
      { e: '😣', k: ['perseverar', 'persevere'] },
      { e: '😖', k: ['confundido', 'angustia'] },
      { e: '😫', k: ['cansado', 'tired'] },
      { e: '😩', k: ['agotado', 'weary'] },
      { e: '🥺', k: ['suplica', 'pleading', 'ojitos'] },
      { e: '😢', k: ['llorar', 'cry', 'triste'] },
      { e: '😭', k: ['llorar', 'sob', 'fuerte'] },
      { e: '😤', k: ['enojo', 'vapor', 'huff'] },
      { e: '😠', k: ['enojado', 'angry'] },
      { e: '😡', k: ['furioso', 'rage', 'rojo'] },
      { e: '🤬', k: ['groseria', 'cursing', 'enojo'] },
      { e: '🤯', k: ['explotar', 'mind blown'] },
      { e: '😳', k: ['sonrojo', 'flushed', 'verguenza'] },
      { e: '🥵', k: ['calor', 'hot', 'sudor'] },
      { e: '🥶', k: ['frio', 'cold', 'congelado'] },
      { e: '😱', k: ['grito', 'scream', 'miedo'] },
      { e: '😨', k: ['miedo', 'fearful'] },
      { e: '😰', k: ['ansiedad', 'sudor', 'anxious'] },
      { e: '😥', k: ['triste', 'alivio', 'sad'] },
      { e: '🤗', k: ['abrazo', 'hug'] },
      { e: '🤔', k: ['pensar', 'thinking', 'duda'] },
      { e: '🤭', k: ['ups', 'risita', 'giggle'] },
      { e: '🤫', k: ['silencio', 'shh', 'quiet'] },
      { e: '🤥', k: ['mentira', 'lie', 'pinocho'] },
      { e: '😬', k: ['mueca', 'grimace', 'nervioso'] },
      { e: '🙄', k: ['ojos', 'roll eyes', 'fastidio'] },
      { e: '😴', k: ['dormir', 'sleep', 'sueño'] },
      { e: '🤤', k: ['baba', 'drool'] },
      { e: '😪', k: ['sueño', 'sleepy'] },
      { e: '😵', k: ['mareado', 'dizzy'] },
      { e: '🤐', k: ['boca cerrada', 'zipper'] },
      { e: '🥴', k: ['mareado', 'woozy', 'borracho'] },
      { e: '🤢', k: ['nausea', 'asco', 'sick'] },
      { e: '🤮', k: ['vomito', 'vomit'] },
      { e: '🤧', k: ['estornudo', 'sneeze', 'gripa'] },
      { e: '😷', k: ['cubrebocas', 'mask', 'enfermo'] },
      { e: '🤒', k: ['termometro', 'fever', 'enfermo'] },
      { e: '🤕', k: ['herida', 'venda', 'hurt'] },
      { e: '🤑', k: ['dinero', 'money', 'rico'] },
      { e: '🤠', k: ['vaquero', 'cowboy'] },
      { e: '😈', k: ['diablo', 'devil', 'travieso'] },
      { e: '👿', k: ['diablo', 'enojado', 'imp'] },
      { e: '💀', k: ['calavera', 'skull', 'muerto'] },
      { e: '👻', k: ['fantasma', 'ghost'] },
      { e: '👽', k: ['alien', 'extraterrestre'] },
      { e: '🤖', k: ['robot', 'bot'] },
      { e: '💩', k: ['popo', 'caca', 'poop'] },
      { e: '🤡', k: ['payaso', 'clown'] },
    ],
  },
  {
    id: 'gestures',
    label: 'Gestos y personas',
    glyph: '👍',
    emojis: [
      { e: '👍', k: ['ok', 'bien', 'thumbs up', 'like', 'aprobado'] },
      { e: '👎', k: ['mal', 'thumbs down', 'dislike'] },
      { e: '👌', k: ['perfecto', 'ok', 'okay'] },
      { e: '🤌', k: ['italiano', 'pinch'] },
      { e: '✌️', k: ['paz', 'victoria', 'peace'] },
      { e: '🤞', k: ['suerte', 'crossed fingers'] },
      { e: '🤟', k: ['te amo', 'love you'] },
      { e: '🤘', k: ['rock', 'cuernos'] },
      { e: '🤙', k: ['llamame', 'call me', 'shaka'] },
      { e: '👈', k: ['izquierda', 'left'] },
      { e: '👉', k: ['derecha', 'right'] },
      { e: '👆', k: ['arriba', 'up'] },
      { e: '👇', k: ['abajo', 'down'] },
      { e: '☝️', k: ['indice', 'point up'] },
      { e: '✋', k: ['mano', 'alto', 'stop'] },
      { e: '🤚', k: ['mano', 'back of hand'] },
      { e: '🖐️', k: ['mano', 'dedos'] },
      { e: '🖖', k: ['vulcano', 'spock'] },
      { e: '👋', k: ['hola', 'adios', 'wave', 'saludo'] },
      { e: '🤝', k: ['trato', 'handshake', 'acuerdo'] },
      { e: '🙏', k: ['gracias', 'porfavor', 'pray', 'rezar'] },
      { e: '✍️', k: ['escribir', 'writing'] },
      { e: '💅', k: ['uñas', 'nails'] },
      { e: '🤳', k: ['selfie'] },
      { e: '💪', k: ['fuerza', 'musculo', 'muscle', 'fuerte'] },
      { e: '🦾', k: ['brazo', 'mecanico'] },
      { e: '👏', k: ['aplausos', 'clap', 'bravo'] },
      { e: '🙌', k: ['celebrar', 'manos arriba', 'praise'] },
      { e: '👐', k: ['manos abiertas', 'open hands'] },
      { e: '🤲', k: ['palmas', 'rezar'] },
      { e: '🤜', k: ['puño', 'fist right'] },
      { e: '🤛', k: ['puño', 'fist left'] },
      { e: '✊', k: ['puño', 'fist', 'fuerza'] },
      { e: '👊', k: ['puño', 'golpe', 'punch'] },
      { e: '🫶', k: ['corazon', 'manos', 'heart hands'] },
      { e: '🫡', k: ['saludo', 'salute'] },
      { e: '🧠', k: ['cerebro', 'brain', 'inteligente'] },
      { e: '👀', k: ['ojos', 'mirar', 'eyes', 'ver'] },
      { e: '👤', k: ['persona', 'usuario', 'user'] },
      { e: '👥', k: ['personas', 'equipo', 'users'] },
      { e: '🧑‍💻', k: ['programador', 'developer', 'tech'] },
      { e: '👨‍🏭', k: ['operador', 'fabrica', 'worker'] },
      { e: '👷', k: ['construccion', 'casco', 'worker'] },
      { e: '🦸', k: ['heroe', 'superheroe', 'hero'] },
    ],
  },
  {
    id: 'nature',
    label: 'Animales y naturaleza',
    glyph: '🐶',
    emojis: [
      { e: '🐶', k: ['perro', 'dog'] },
      { e: '🐱', k: ['gato', 'cat'] },
      { e: '🐭', k: ['raton', 'mouse'] },
      { e: '🐹', k: ['hamster'] },
      { e: '🐰', k: ['conejo', 'rabbit'] },
      { e: '🦊', k: ['zorro', 'fox'] },
      { e: '🐻', k: ['oso', 'bear'] },
      { e: '🐼', k: ['panda'] },
      { e: '🐨', k: ['koala'] },
      { e: '🐯', k: ['tigre', 'tiger'] },
      { e: '🦁', k: ['leon', 'lion'] },
      { e: '🐮', k: ['vaca', 'cow'] },
      { e: '🐷', k: ['cerdo', 'pig'] },
      { e: '🐵', k: ['mono', 'monkey'] },
      { e: '🐔', k: ['pollo', 'gallina', 'chicken'] },
      { e: '🐧', k: ['pinguino', 'penguin'] },
      { e: '🐦', k: ['pajaro', 'bird'] },
      { e: '🦅', k: ['aguila', 'eagle'] },
      { e: '🦉', k: ['buho', 'owl'] },
      { e: '🐝', k: ['abeja', 'bee'] },
      { e: '🦋', k: ['mariposa', 'butterfly'] },
      { e: '🐢', k: ['tortuga', 'turtle'] },
      { e: '🐍', k: ['serpiente', 'snake'] },
      { e: '🐙', k: ['pulpo', 'octopus'] },
      { e: '🐠', k: ['pez', 'fish'] },
      { e: '🐬', k: ['delfin', 'dolphin'] },
      { e: '🐳', k: ['ballena', 'whale'] },
      { e: '🦈', k: ['tiburon', 'shark'] },
      { e: '🐊', k: ['cocodrilo', 'crocodile'] },
      { e: '🦖', k: ['dinosaurio', 'rex'] },
      { e: '🦄', k: ['unicornio', 'unicorn'] },
      { e: '🐴', k: ['caballo', 'horse'] },
      { e: '🌵', k: ['cactus'] },
      { e: '🌲', k: ['arbol', 'pino', 'tree'] },
      { e: '🌳', k: ['arbol', 'tree'] },
      { e: '🌴', k: ['palmera', 'palm'] },
      { e: '🌱', k: ['planta', 'brote', 'seedling'] },
      { e: '🌿', k: ['hierba', 'herb'] },
      { e: '🍀', k: ['trebol', 'suerte', 'clover'] },
      { e: '🌷', k: ['tulipan', 'flor'] },
      { e: '🌹', k: ['rosa', 'flor', 'rose'] },
      { e: '🌻', k: ['girasol', 'sunflower'] },
      { e: '🌸', k: ['flor', 'cerezo', 'blossom'] },
      { e: '🌼', k: ['flor', 'margarita'] },
      { e: '🍄', k: ['hongo', 'mushroom'] },
      { e: '🌍', k: ['mundo', 'tierra', 'earth'] },
      { e: '🌙', k: ['luna', 'moon'] },
      { e: '⭐', k: ['estrella', 'star'] },
      { e: '🌟', k: ['estrella', 'brillo', 'glowing'] },
      { e: '✨', k: ['brillos', 'sparkles', 'magia'] },
      { e: '⚡', k: ['rayo', 'energia', 'bolt'] },
      { e: '🔥', k: ['fuego', 'fire', 'lit'] },
      { e: '💧', k: ['gota', 'agua', 'drop'] },
      { e: '🌊', k: ['ola', 'mar', 'wave'] },
      { e: '🌈', k: ['arcoiris', 'rainbow'] },
      { e: '☀️', k: ['sol', 'sun'] },
      { e: '⛅', k: ['nube', 'sol', 'cloud'] },
      { e: '☁️', k: ['nube', 'cloud'] },
      { e: '❄️', k: ['nieve', 'snow', 'frio'] },
    ],
  },
  {
    id: 'food',
    label: 'Comida y bebida',
    glyph: '🍔',
    emojis: [
      { e: '🍎', k: ['manzana', 'apple'] },
      { e: '🍌', k: ['platano', 'banana'] },
      { e: '🍇', k: ['uvas', 'grapes'] },
      { e: '🍓', k: ['fresa', 'strawberry'] },
      { e: '🍊', k: ['naranja', 'orange'] },
      { e: '🍉', k: ['sandia', 'watermelon'] },
      { e: '🍑', k: ['durazno', 'peach'] },
      { e: '🍍', k: ['piña', 'pineapple'] },
      { e: '🥑', k: ['aguacate', 'avocado'] },
      { e: '🍅', k: ['tomate', 'tomato'] },
      { e: '🌽', k: ['elote', 'maiz', 'corn'] },
      { e: '🌶️', k: ['chile', 'picante', 'pepper'] },
      { e: '🥕', k: ['zanahoria', 'carrot'] },
      { e: '🥖', k: ['pan', 'baguette'] },
      { e: '🧀', k: ['queso', 'cheese'] },
      { e: '🥚', k: ['huevo', 'egg'] },
      { e: '🍳', k: ['huevo', 'sarten', 'cooking'] },
      { e: '🥞', k: ['hotcakes', 'pancakes'] },
      { e: '🥓', k: ['tocino', 'bacon'] },
      { e: '🍔', k: ['hamburguesa', 'burger'] },
      { e: '🍟', k: ['papas', 'fries'] },
      { e: '🍕', k: ['pizza'] },
      { e: '🌭', k: ['hotdog'] },
      { e: '🌮', k: ['taco'] },
      { e: '🌯', k: ['burrito'] },
      { e: '🥗', k: ['ensalada', 'salad'] },
      { e: '🍜', k: ['ramen', 'sopa', 'noodles'] },
      { e: '🍣', k: ['sushi'] },
      { e: '🍤', k: ['camaron', 'shrimp'] },
      { e: '🍦', k: ['helado', 'ice cream'] },
      { e: '🍩', k: ['dona', 'donut'] },
      { e: '🍪', k: ['galleta', 'cookie'] },
      { e: '🎂', k: ['pastel', 'cumpleaños', 'cake'] },
      { e: '🍰', k: ['pastel', 'rebanada', 'cake'] },
      { e: '🧁', k: ['cupcake', 'panque'] },
      { e: '🍫', k: ['chocolate'] },
      { e: '🍬', k: ['dulce', 'candy'] },
      { e: '🍭', k: ['paleta', 'lollipop'] },
      { e: '🍿', k: ['palomitas', 'popcorn'] },
      { e: '☕', k: ['cafe', 'coffee'] },
      { e: '🍵', k: ['te', 'tea'] },
      { e: '🥤', k: ['refresco', 'soda'] },
      { e: '🧋', k: ['boba', 'bubble tea'] },
      { e: '🍺', k: ['cerveza', 'beer'] },
      { e: '🍻', k: ['cervezas', 'salud', 'cheers'] },
      { e: '🥂', k: ['brindis', 'champagne', 'cheers'] },
      { e: '🍷', k: ['vino', 'wine'] },
      { e: '🍸', k: ['coctel', 'cocktail'] },
      { e: '🍾', k: ['champaña', 'celebrar'] },
    ],
  },
  {
    id: 'activities',
    label: 'Actividades',
    glyph: '⚽',
    emojis: [
      { e: '⚽', k: ['futbol', 'soccer', 'balon'] },
      { e: '🏀', k: ['basquet', 'basketball'] },
      { e: '🏈', k: ['futbol americano', 'football'] },
      { e: '⚾', k: ['beisbol', 'baseball'] },
      { e: '🎾', k: ['tenis', 'tennis'] },
      { e: '🏐', k: ['voleibol', 'volleyball'] },
      { e: '🏉', k: ['rugby'] },
      { e: '🎱', k: ['billar', 'pool'] },
      { e: '🏓', k: ['ping pong'] },
      { e: '🏸', k: ['badminton'] },
      { e: '🥊', k: ['box', 'boxing', 'guante'] },
      { e: '🥋', k: ['karate', 'judo'] },
      { e: '⛳', k: ['golf'] },
      { e: '🎯', k: ['diana', 'objetivo', 'target'] },
      { e: '🎳', k: ['boliche', 'bowling'] },
      { e: '🎮', k: ['videojuego', 'gaming', 'control'] },
      { e: '🕹️', k: ['joystick', 'arcade'] },
      { e: '🎲', k: ['dado', 'dice', 'azar'] },
      { e: '🧩', k: ['rompecabezas', 'puzzle'] },
      { e: '🎨', k: ['arte', 'pintura', 'art'] },
      { e: '🎭', k: ['teatro', 'drama'] },
      { e: '🎬', k: ['cine', 'pelicula', 'movie'] },
      { e: '🎤', k: ['microfono', 'cantar', 'mic'] },
      { e: '🎧', k: ['audifonos', 'headphones'] },
      { e: '🎵', k: ['musica', 'nota', 'music'] },
      { e: '🎸', k: ['guitarra', 'guitar'] },
      { e: '🎹', k: ['piano', 'teclado'] },
      { e: '🥁', k: ['bateria', 'drums', 'tambor'] },
      { e: '🏆', k: ['trofeo', 'ganador', 'trophy'] },
      { e: '🥇', k: ['oro', 'primero', 'gold'] },
      { e: '🥈', k: ['plata', 'segundo', 'silver'] },
      { e: '🥉', k: ['bronce', 'tercero', 'bronze'] },
      { e: '🏅', k: ['medalla', 'medal'] },
      { e: '🎖️', k: ['medalla', 'militar'] },
      { e: '🎁', k: ['regalo', 'gift', 'present'] },
      { e: '🎉', k: ['fiesta', 'celebrar', 'party', 'tada'] },
      { e: '🎊', k: ['confeti', 'fiesta', 'confetti'] },
      { e: '🎈', k: ['globo', 'balloon'] },
      { e: '🎀', k: ['moño', 'lazo', 'bow'] },
      { e: '🎄', k: ['navidad', 'arbol', 'christmas'] },
    ],
  },
  {
    id: 'travel',
    label: 'Viajes y lugares',
    glyph: '🚗',
    emojis: [
      { e: '🚗', k: ['auto', 'carro', 'car'] },
      { e: '🚕', k: ['taxi'] },
      { e: '🚙', k: ['suv', 'camioneta'] },
      { e: '🚌', k: ['autobus', 'bus'] },
      { e: '🚓', k: ['patrulla', 'policia'] },
      { e: '🚑', k: ['ambulancia'] },
      { e: '🚒', k: ['bomberos'] },
      { e: '🚚', k: ['camion', 'truck', 'envio'] },
      { e: '🚛', k: ['trailer', 'camion'] },
      { e: '🏍️', k: ['moto', 'motorcycle'] },
      { e: '🚲', k: ['bici', 'bicicleta', 'bike'] },
      { e: '✈️', k: ['avion', 'vuelo', 'plane'] },
      { e: '🚀', k: ['cohete', 'rocket', 'lanzar'] },
      { e: '🛸', k: ['ovni', 'ufo'] },
      { e: '🚁', k: ['helicoptero'] },
      { e: '⛵', k: ['velero', 'barco'] },
      { e: '🚢', k: ['barco', 'ship'] },
      { e: '🚂', k: ['tren', 'train'] },
      { e: '🗽', k: ['libertad', 'estatua', 'ny'] },
      { e: '🗼', k: ['torre', 'tokyo'] },
      { e: '🏰', k: ['castillo', 'castle'] },
      { e: '🏠', k: ['casa', 'home', 'house'] },
      { e: '🏢', k: ['oficina', 'edificio', 'office'] },
      { e: '🏭', k: ['fabrica', 'factory', 'planta'] },
      { e: '🏥', k: ['hospital'] },
      { e: '🏦', k: ['banco', 'bank'] },
      { e: '🏬', k: ['tienda', 'centro comercial'] },
      { e: '🏗️', k: ['construccion', 'grua'] },
      { e: '🗺️', k: ['mapa', 'map'] },
      { e: '🧭', k: ['brujula', 'compass'] },
      { e: '🏖️', k: ['playa', 'beach'] },
      { e: '⛰️', k: ['montaña', 'mountain'] },
      { e: '🌋', k: ['volcan', 'volcano'] },
      { e: '🗿', k: ['moai', 'estatua'] },
      { e: '🎢', k: ['montaña rusa', 'roller'] },
      { e: '🎡', k: ['rueda', 'feria', 'ferris'] },
      { e: '🚦', k: ['semaforo', 'traffic'] },
      { e: '⛽', k: ['gasolina', 'gas'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objetos',
    glyph: '💡',
    emojis: [
      { e: '💡', k: ['idea', 'foco', 'bulb', 'light'] },
      { e: '🔦', k: ['linterna', 'flashlight'] },
      { e: '🔋', k: ['bateria', 'battery'] },
      { e: '🔌', k: ['enchufe', 'plug'] },
      { e: '💻', k: ['laptop', 'computadora', 'pc'] },
      { e: '🖥️', k: ['monitor', 'desktop', 'pc'] },
      { e: '⌨️', k: ['teclado', 'keyboard'] },
      { e: '🖱️', k: ['mouse', 'raton'] },
      { e: '🖨️', k: ['impresora', 'printer'] },
      { e: '📱', k: ['celular', 'telefono', 'phone', 'movil'] },
      { e: '☎️', k: ['telefono', 'phone'] },
      { e: '📞', k: ['llamada', 'telefono', 'call'] },
      { e: '📷', k: ['camara', 'foto', 'camera'] },
      { e: '🎥', k: ['camara', 'video', 'cine'] },
      { e: '📹', k: ['videocamara', 'video'] },
      { e: '🔍', k: ['lupa', 'buscar', 'search'] },
      { e: '🔒', k: ['candado', 'seguro', 'lock'] },
      { e: '🔓', k: ['abierto', 'unlock'] },
      { e: '🔑', k: ['llave', 'key'] },
      { e: '🗝️', k: ['llave', 'antigua'] },
      { e: '🔨', k: ['martillo', 'hammer'] },
      { e: '🛠️', k: ['herramientas', 'tools'] },
      { e: '🔧', k: ['llave', 'wrench', 'tuerca'] },
      { e: '🔩', k: ['tornillo', 'tuerca', 'bolt'] },
      { e: '⚙️', k: ['engrane', 'gear', 'config'] },
      { e: '🧰', k: ['caja herramientas', 'toolbox'] },
      { e: '🧲', k: ['iman', 'magnet'] },
      { e: '⚗️', k: ['quimica', 'experimento'] },
      { e: '🧪', k: ['tubo', 'prueba', 'lab'] },
      { e: '🔬', k: ['microscopio', 'lab'] },
      { e: '🧬', k: ['adn', 'dna'] },
      { e: '💊', k: ['pastilla', 'medicina', 'pill'] },
      { e: '🩺', k: ['estetoscopio', 'medico'] },
      { e: '📦', k: ['caja', 'paquete', 'box', 'package'] },
      { e: '📬', k: ['buzon', 'correo', 'mail'] },
      { e: '✉️', k: ['correo', 'sobre', 'email'] },
      { e: '📨', k: ['correo', 'mensaje', 'mail'] },
      { e: '📅', k: ['calendario', 'fecha', 'calendar'] },
      { e: '📆', k: ['calendario', 'fecha'] },
      { e: '📌', k: ['pin', 'chincheta'] },
      { e: '📎', k: ['clip', 'adjunto', 'paperclip'] },
      { e: '✂️', k: ['tijeras', 'scissors', 'cortar'] },
      { e: '📏', k: ['regla', 'ruler', 'medir'] },
      { e: '📐', k: ['escuadra', 'angulo'] },
      { e: '📝', k: ['nota', 'escribir', 'memo'] },
      { e: '📋', k: ['portapapeles', 'clipboard', 'tarea'] },
      { e: '📊', k: ['grafica', 'barras', 'chart'] },
      { e: '📈', k: ['subida', 'crecer', 'up chart'] },
      { e: '📉', k: ['bajada', 'caer', 'down chart'] },
      { e: '💰', k: ['dinero', 'bolsa', 'money'] },
      { e: '💵', k: ['billete', 'dolar', 'cash'] },
      { e: '💳', k: ['tarjeta', 'card', 'pago'] },
      { e: '⏰', k: ['alarma', 'reloj', 'alarm'] },
      { e: '⏳', k: ['reloj arena', 'tiempo', 'hourglass'] },
      { e: '🔔', k: ['campana', 'notificacion', 'bell'] },
      { e: '📢', k: ['altavoz', 'anuncio', 'megafono'] },
      { e: '🏷️', k: ['etiqueta', 'tag', 'precio'] },
      { e: '🛒', k: ['carrito', 'compras', 'cart'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Símbolos',
    glyph: '❤️',
    emojis: [
      { e: '❤️', k: ['amor', 'corazon', 'heart', 'rojo'] },
      { e: '🧡', k: ['corazon', 'naranja', 'orange heart'] },
      { e: '💛', k: ['corazon', 'amarillo', 'yellow'] },
      { e: '💚', k: ['corazon', 'verde', 'green'] },
      { e: '💙', k: ['corazon', 'azul', 'blue'] },
      { e: '💜', k: ['corazon', 'morado', 'purple'] },
      { e: '🖤', k: ['corazon', 'negro', 'black'] },
      { e: '🤍', k: ['corazon', 'blanco', 'white'] },
      { e: '💔', k: ['roto', 'broken heart'] },
      { e: '❣️', k: ['corazon', 'exclamacion'] },
      { e: '💕', k: ['corazones', 'two hearts'] },
      { e: '💞', k: ['corazones', 'girando'] },
      { e: '💓', k: ['latido', 'beating heart'] },
      { e: '💗', k: ['creciendo', 'growing heart'] },
      { e: '💖', k: ['brillante', 'sparkling heart'] },
      { e: '💘', k: ['flecha', 'cupido', 'arrow'] },
      { e: '💝', k: ['regalo', 'corazon', 'gift heart'] },
      { e: '✅', k: ['check', 'listo', 'ok', 'hecho', 'done'] },
      { e: '☑️', k: ['check', 'casilla', 'checkbox'] },
      { e: '✔️', k: ['palomita', 'check'] },
      { e: '❌', k: ['error', 'no', 'cross', 'mal'] },
      { e: '❎', k: ['x', 'cancelar'] },
      { e: '➕', k: ['mas', 'plus', 'sumar'] },
      { e: '➖', k: ['menos', 'minus', 'restar'] },
      { e: '➗', k: ['division', 'divide'] },
      { e: '✖️', k: ['multiplicar', 'x'] },
      { e: '♾️', k: ['infinito', 'infinity'] },
      { e: '❗', k: ['exclamacion', 'importante'] },
      { e: '❓', k: ['pregunta', 'duda', 'question'] },
      { e: '⚠️', k: ['advertencia', 'cuidado', 'warning'] },
      { e: '🚫', k: ['prohibido', 'no', 'forbidden'] },
      { e: '✋', k: ['alto', 'stop'] },
      { e: '💯', k: ['cien', 'perfecto', '100'] },
      { e: '🔥', k: ['fuego', 'fire'] },
      { e: '⭐', k: ['estrella', 'star'] },
      { e: '🌟', k: ['estrella', 'brillo'] },
      { e: '💫', k: ['mareo', 'estrella', 'dizzy'] },
      { e: '⚡', k: ['rayo', 'bolt'] },
      { e: '💥', k: ['choque', 'boom', 'explosion'] },
      { e: '💦', k: ['gotas', 'sudor', 'sweat'] },
      { e: '💨', k: ['rapido', 'viento', 'dash'] },
      { e: '🕐', k: ['hora', 'reloj', 'clock'] },
      { e: '✳️', k: ['asterisco', 'eight'] },
      { e: '🔆', k: ['brillo', 'bright'] },
      { e: '♻️', k: ['reciclar', 'recycle'] },
      { e: '🆗', k: ['ok', 'aprobado'] },
      { e: '🆕', k: ['nuevo', 'new'] },
      { e: '🆙', k: ['arriba', 'up'] },
      { e: '🔝', k: ['top', 'arriba'] },
      { e: '🔙', k: ['regresar', 'back'] },
      { e: '🔜', k: ['pronto', 'soon'] },
      { e: '#️⃣', k: ['hashtag', 'numeral'] },
      { e: '🔢', k: ['numeros', 'numbers'] },
    ],
  },
];

/** Aplana todos los emojis (para búsqueda global). */
const ALL_EMOJIS: { e: string; k: string[] }[] = EMOJI_CATEGORIES.flatMap(
  (c) => c.emojis,
);

/**
 * Busca emojis por término (en palabras clave). Vacío → []. El llamador decide
 * mostrar las categorías cuando no hay búsqueda.
 */
export function searchEmojis(term: string, limit = 60): string[] {
  const q = term.trim().toLowerCase();
  if (!q) return [];
  const out: string[] = [];
  for (const item of ALL_EMOJIS) {
    if (item.k.some((kw) => kw.includes(q))) {
      out.push(item.e);
      if (out.length >= limit) break;
    }
  }
  return out;
}

/** Conjunto reducido de reacciones rápidas (toolbar de cada mensaje). */
export const QUICK_REACTIONS = ['👍', '❤️', '😂', '🎉', '✅', '👀', '🔥', '🙏'];
