import {
  Body,
  Controller,
  Get,
  Param,
  ParseIntPipe,
  Post,
  Query,
  Request,
  UseGuards,
} from '@nestjs/common';
import { ApiOperation, ApiQuery, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { AutopilotService } from './autopilot.service';
import { ExecuteProposalDto, ListProposalsQueryDto } from './dto/autopilot.dto';
import { CorrectiveProposal } from './entities/corrective-proposal.entity';

@ApiTags('Autopilot')
@UseGuards(JwtAuthGuard)
@Controller('autopilot')
export class AutopilotController {
  constructor(private readonly autopilot: AutopilotService) {}

  @Get('proposals')
  @ApiOperation({
    summary: 'List active Autopilot recommendations',
    description:
      'Returns CorrectiveProposals generated by the 5-minute scan of ' +
      'bottleneck hotspots (SeverityScore > 0.7) and sigma instability ' +
      '(SigmaLevel < 2.0). Filter by status=pending|executed|dismissed|expired.',
  })
  @ApiQuery({ name: 'status',   required: false, description: 'Proposal status filter' })
  @ApiQuery({ name: 'tenantId', required: false, description: 'Tenant / building ID filter' })
  listProposals(
    @Query() query: ListProposalsQueryDto,
  ): Promise<CorrectiveProposal[]> {
    return this.autopilot.listProposals(query.status, query.tenantId);
  }

  @Post('proposals/:id/execute')
  @ApiOperation({
    summary: 'One-Click Fix — execute an Autopilot proposal',
    description:
      'Executes the corrective action encoded in the proposal:\n' +
      '  • wip_rebalance      — Puts lowest-priority WIP on_hold to relieve bottleneck\n' +
      '  • resupply_trigger   — Creates an urgent Resupply record\n' +
      '  • maintenance_audit  — Emits a real-time maintenance signal\n\n' +
      'Marks the proposal as executed and records the actor.',
  })
  executeProposal(
    @Param('id', ParseIntPipe) id: number,
    @Body() dto: ExecuteProposalDto,
    @Request() req: any,
  ) {
    const actor = dto.actor ?? req.user?.username ?? req.user?.email;
    return this.autopilot.executeProposal(id, actor);
  }
}
