import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  Index,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';
import { DATE_COLUMN_TYPE } from '../../../common/database/date-column-type';

export type RequisitionSource = 'mrp' | 'manual';
export type RequisitionStatus = 'open' | 'converted' | 'cancelled';

/** Purchase requisition (ME51N) — demand signal, usually generated by the MRP run. */
@Entity('erp_purchase_requisitions')
export class ErpPurchaseRequisition {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', length: 32 })
  @Index({ unique: true })
  prNumber: string;

  @Column({ type: 'varchar', length: 100 })
  @Index()
  partNumber: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  description: string | null;

  @Column({ type: 'float' })
  quantity: number;

  @Column({ type: DATE_COLUMN_TYPE, nullable: true })
  needBy: Date | null;

  @Column({ type: 'varchar', length: 8, default: 'manual' })
  source: RequisitionSource;

  @Column({ type: 'varchar', length: 16, default: 'open' })
  @Index()
  status: RequisitionStatus;

  @Column({ type: 'int', nullable: true })
  suggestedSupplierId: number | null;

  @Column({ type: 'int', nullable: true })
  mrpRunId: number | null;

  @Column({ type: 'int', nullable: true })
  purchaseOrderId: number | null;

  @Column({ type: 'varchar', length: 255, nullable: true })
  notes: string | null;

  @Column({ type: 'varchar', length: 120, nullable: true })
  createdBy: string | null;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
