export interface FormulaCatalogArg { name: string; desc: string; optional?: boolean }
export interface FormulaCatalogEntry { name: string; syntax: string; desc: string; args: FormulaCatalogArg[]; example: string }

const A = (name: string, desc: string, optional = false): FormulaCatalogArg => ({ name, desc, optional });

export const AXOS_FORMULA_CATALOG: FormulaCatalogEntry[] = [
  { name: 'AXOS_OEE', syntax: 'AXOS_OEE(disponibilidad; performance; calidad)', desc: 'Calcula OEE multiplicando disponibilidad, performance y calidad.', args: [A('disponibilidad', 'Disponibilidad 0–1.'), A('performance', 'Performance 0–1.'), A('calidad', 'Calidad 0–1.')], example: '=AXOS_OEE(C2;D2;E2)' },
  { name: 'AXOS_YIELD', syntax: 'AXOS_YIELD(buenas; total)', desc: 'Rendimiento de piezas buenas sobre total producido.', args: [A('buenas', 'Cantidad buena.'), A('total', 'Cantidad total.')], example: '=AXOS_YIELD(F2;G2)' },
  { name: 'AXOS_SCRAP_RATE', syntax: 'AXOS_SCRAP_RATE(scrap; total)', desc: 'Tasa de scrap sobre total producido.', args: [A('scrap', 'Cantidad scrap.'), A('total', 'Cantidad total.')], example: '=AXOS_SCRAP_RATE(H2;G2)' },
  { name: 'AXOS_CPK', syntax: 'AXOS_CPK(valores; LSL; USL)', desc: 'Capacidad de proceso Cpk contra límites de especificación.', args: [A('valores', 'Rango de mediciones.'), A('LSL', 'Límite inferior.'), A('USL', 'Límite superior.')], example: '=AXOS_CPK(B2:B50;9.8;10.2)' },
  { name: 'AXOS_INVENTORY_TURNS', syntax: 'AXOS_INVENTORY_TURNS(cogs; inventario_prom)', desc: 'Vueltas de inventario a partir de costo de ventas e inventario promedio.', args: [A('cogs', 'Costo de ventas.'), A('inventario_prom', 'Inventario promedio.')], example: '=AXOS_INVENTORY_TURNS(C2;D2)' },
  { name: 'AXOS_ABCD_CLASS', syntax: 'AXOS_ABCD_CLASS(valor; umbralA; umbralB; umbralC)', desc: 'Clasificación ABCD por valor o porcentaje acumulado.', args: [A('valor', 'Valor evaluado.'), A('umbralA', 'Umbral clase A.'), A('umbralB', 'Umbral clase B.'), A('umbralC', 'Umbral clase C.', true)], example: '=AXOS_ABCD_CLASS(F2;0.8;0.95;0.99)' },
  { name: 'AXOS_MARGIN', syntax: 'AXOS_MARGIN(precio; costo)', desc: 'Margen bruto (precio - costo) / precio.', args: [A('precio', 'Precio de venta.'), A('costo', 'Costo total.')], example: '=AXOS_MARGIN(H2;G2)' },
  { name: 'AXOS_MARKUP', syntax: 'AXOS_MARKUP(precio; costo)', desc: 'Markup sobre costo (precio - costo) / costo.', args: [A('precio', 'Precio de venta.'), A('costo', 'Costo total.')], example: '=AXOS_MARKUP(H2;G2)' },
  { name: 'AXOS_COST_ROLLUP', syntax: 'AXOS_COST_ROLLUP(qty; costo; [scrap])', desc: 'Rollup de costo extendido con scrap opcional por componente.', args: [A('qty', 'Rango de cantidades.'), A('costo', 'Rango de costos unitarios.'), A('scrap', 'Rango de scrap 0–1.', true)], example: '=AXOS_COST_ROLLUP(D2:D20;E2:E20;F2:F20)' },
  { name: 'AXOS_SUPPLIER_SCORE', syntax: 'AXOS_SUPPLIER_SCORE(otd; calidad; costo; respuesta; [pesos])', desc: 'Score ponderado de proveedor para compras/calidad.', args: [A('otd', 'On-time delivery 0–1.'), A('calidad', 'Calidad 0–1.'), A('costo', 'Score costo 0–1.'), A('respuesta', 'Respuesta 0–1.'), A('pesos', 'Pesos opcionales.', true)], example: '=AXOS_SUPPLIER_SCORE(B2;C2;D2;E2)' },
  { name: 'AXOS_CAPACITY_UTILIZATION', syntax: 'AXOS_CAPACITY_UTILIZATION(demanda_horas; capacidad_horas)', desc: 'Utilización de capacidad para planes de producción.', args: [A('demanda_horas', 'Horas requeridas.'), A('capacidad_horas', 'Horas disponibles.')], example: '=AXOS_CAPACITY_UTILIZATION(F2;G2)' },
  { name: 'AXOS_SHORTAGE', syntax: 'AXOS_SHORTAGE(requerido; disponible; [incoming])', desc: 'Faltante neto considerando disponible e incoming.', args: [A('requerido', 'Cantidad requerida.'), A('disponible', 'Cantidad disponible.'), A('incoming', 'Entradas futuras.', true)], example: '=AXOS_SHORTAGE(B2;C2;D2)' },
  { name: 'AXOS_SUM_VISIBLE', syntax: 'AXOS_SUM_VISIBLE(valores)', desc: 'Suma valores visibles/filtrados cuando se usa con rangos preparados.', args: [A('valores', 'Rango de valores.')], example: '=AXOS_SUM_VISIBLE(G2:G100)' },
];
